apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-lab-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-lab-web
  template:
    metadata:
      labels:
        app: gitops-lab-web
    spec:
      containers:
        - name: web
          #image: ghcr.io/dtaixp/gitops-lab-web:25b426c
          image: ghcr.io/dtaixp/gitops-lab-web:25b426c
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80